### ISSUE TITLE
ResponseFactory doesn't implement the correct interface

### ISSUE THREAD

**Issue by delboy1978uk** [http-interop/http-factory-diactoros#19]
I tried to add your ResponseFactory to my PSR-15 Dispatcher, but it cracked up saying that it must implement `Psr\Http\Message\ResponseFactoryInterface`. Currently it implements `Interop\Http\Factory\ResponseFactoryInterface`, which it doesn't like.

**Comment by shadowhand** [comment]
`Psr\Http\Message\ResponseFactoryInterface` doesn't exist in any package. Where are you seeing this?

**Comment by delboy1978uk** [comment]
Right. Interop\Http\Factory\ResponseFactoryInterface has the same methods as a Psr one, but it isn't defined (yet). In the http-factory repo, the interface should be defined with the Psr namespace until an official Psr package is available. I'll close this issue and reopen it on the other repo.
